name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Set up Just
        uses: extractions/setup-just@v3

      - name: Build binaries
        run: VERSION=devel just build
